before:
  hooks:
    - make dep
    
builds:
  - main: .
    id: "postpilot"
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      # important for reproducible builds so full build paths and module paths
      # are not embedded.
      - -trimpath
    ldflags:
      # disable symbol table (-s) and DWARF generation (-w)
      - -s -w -X main.Version={{.Version}} -X main.useWails=true
    gcflags:
      - all=-N -l
    tags:
      - dev
    overrides:
      - goos: windows
        goarch: amd64
        goamd64: v1
        ldflags:
          - -w
          - -s
          - -h
          - -X main.Version={{.Version}}
          - -X main.useWails=true
