project_name: postpilot
builds:
  - id: postpilot
    binary: postpilot
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - wails build -platform linux/amd64 -o ../dist/postpilot_linux_amd64/postpilot

nfpms:
  - id: postpilot
    package_name: postpilot
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Chris Watson
    homepage: https://postpilot.watzon.tech
    maintainer: Chris Watson <cawatson1993@gmail.com>
    description: Test SMTP server and frontend client for local development
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
    contents:
      - src: build/linux/postpilot_0.0.0_ARCH/usr/share/applications/postpilot.desktop
        dst: /usr/share/applications/postpilot.desktop
      - src: build/linux/postpilot_0.0.0_ARCH/usr/share/icons/hicolor/512x512/apps/postpilot.png
        dst: /usr/share/icons/hicolor/512x512/apps/postpilot.png
      - src: build/linux/postpilot_0.0.0_ARCH/usr/share/metainfo/tech.watzon.postman.appdata.xml
        dst: /usr/share/metainfo/tech.watzon.postman.appdata.xml 