before:
  hooks:
    - make dep
    - make bindings
    
builds:
  - main: .
    id: "postpilot"
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      # important for reproducible builds so full build paths and module paths
      # are not embedded.
      - -trimpath
    ldflags:
      # disable symbol table (-s) and DWARF generation (-w)
      - -s -w -X main.Version={{.Version}} -X main.useWails=true
    tags:
      - desktop
      - production
    overrides:
      - goos: windows
        goarch: amd64
        goamd64: v1
        ldflags:
          - -w
          - -s
          - -h
          - -H windowsgui
          - -X main.Version={{.Version}}
          - -X main.useWails=true
        tags:
          - desktop
          - production

archives:
  - format: tar.gz
    # this template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

# config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: 'checksums.txt'

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: false

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't
# need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
    - "--yes" # needed on cosign 2.0.0+
  artifacts: checksum
  output: true

# Configure generation of a development full build snapshot
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - vendor: postpilot
    license: MIT
    homepage: https://postpilot.watzon.tech
    maintainer: "Watzon <cawatson1993@gmail.com>"
    description: "Email and SMTP testing GUI for developers"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/local/bin
    contents:
      - src: ./build/linux/postpilot_0.0.0_ARCH/usr/share/applications/postpilot.desktop
        dst: /usr/share/applications/postpilot.desktop
      - src: ./build/linux/postpilot_0.0.0_ARCH/usr/share/icons/hicolor/512x512/apps/postpilot.png
        dst: /usr/share/icons/hicolor/512x512/apps/postpilot.png
      - src: ./build/linux/postpilot_0.0.0_ARCH/usr/share/metainfo/tech.watzon.postpilot.appdata.xml
        dst: /usr/share/metainfo/tech.watzon.postpilot.appdata.xml
    dependencies:
      # Core Wails dependencies
      - gtk3
      - webkit2gtk-4.0
      - libayatana-appindicator3-1  # For system tray support
      
      # Additional runtime dependencies
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - xdg-utils                    # For opening URLs in browser
    overrides:
      rpm:
        dependencies:
          - gtk3
          - webkit2gtk4.0
          - libappindicator-gtk3      # RedHat/Fedora equivalent
          - webkit2gtk3
      apk:
        dependencies:
          - gtk+3.0
          - webkit2gtk
          - libappindicator
      archlinux:
        dependencies:
          - gtk3
          - webkit2gtk
          - libappindicator-gtk3
    rpm:
      packager: "Watzon <cawatson1993@gmail.com>"
    deb:
      fields:
        Maintainer: "Watzon <cawatson1993@gmail.com>"
        Bugs: https://github.com/watzon/postpilot/issues
    archlinux:
      packager: "Watzon <cawatson1993@gmail.com>"

