// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSpam(arg1) {
  return window['go']['main']['App']['CheckSpam'](arg1);
}

export function ClearEmails() {
  return window['go']['main']['App']['ClearEmails']();
}

export function GetEmails() {
  return window['go']['main']['App']['GetEmails']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function RestartSMTPServer() {
  return window['go']['main']['App']['RestartSMTPServer']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
