// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spam} from '../models';
import {main} from '../models';

export function CheckSpam(arg1:string):Promise<spam.SpamReport>;

export function ClearEmails():Promise<void>;

export function GetEmails():Promise<Array<main.Email>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function RestartSMTPServer():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
