// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEmails():Promise<Array<main.Email>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
